#!/usr/bin/env bash
#

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [ $# -eq 4 ]; then
		scp -o StritHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
	elif [ $# -eq 3 ]; then
		scp -o StritHostKeyChecking=no "$1" "$3@$2:~/"
	fi
fi
