#!/usr/bin/env bash
# install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 777 /var/www/html
sudo echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo service nginx start
