#!/usr/bin/env bash
# installing load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo echo "
frontend haproxy-main
	bind *:80
	default_backend bck_webservers
backend bck_webservers
	balance roundrobin
	server 4383-web-01 54.160.62.128:80 check
	server 4383-web-02 3.89.99.18:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
