#!/usr/bin/env bash
# bash script generates mysql dump and creates a compressed fil backup.sql

mysqldump -u root -p"$1" --all-databases --master-data | sudo tee backup.sql 
tar -czvf "$(date +%m-%d-%Y).tar.gz" backup.sql 
