#!/usr/bin/env bash
# debuging, nginx listnig 80

sudo service nginx stop
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo service nginx start
