#!/usr/bin/env bash
#cfizz buzz

for counter in {1..100}
do
    if [ "$((counter % 5))" == 0 ] && [ "$((counter % 3))" == 0 ]
    then
        echo "FizzBuzz"
    elif [ "$((counter % 3))" == 0 ]
    then
        echo "Fizz"
    elif [ "$((counter % 5))" == 0 ]
    then
        echo "Buzz"
    else
        echo $counter
    fi
done
