#!/usr/bin/env bash
# display a text n times with a while, and in after 9 impression print hii

i=1
while [ $i -le 10 ]
	do
		echo "Best School"
		if [[ $i -eq 9 ]]
		then
			echo "Hi"
		fi
		i=$(( i + 1 ))
done
