#!/usr/bin/env bash
#configure Ubuntu server with same requirements

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.[1-9]/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8\tfacebbok.com">> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

