#!/usr/bin/env bash
# bash script that ngix run as nginx user
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
